export const data = [
	{ option: '0', style: { backgroundColor: 'green', textColor: 'white' } },
	{ option: '32', style: { backgroundColor: 'red', textColor: 'white' } },
	{ option: '15', style: { backgroundColor: 'black', textColor: 'white' } },
	{ option: '19', style: { backgroundColor: 'red', textColor: 'white' } },
	{ option: '4', style: { backgroundColor: 'black', textColor: 'white' } },
	{ option: '21', style: { backgroundColor: 'red', textColor: 'white' } },
	{ option: '2', style: { backgroundColor: 'black', textColor: 'white' } },
	{ option: '25', style: { backgroundColor: 'red', textColor: 'white' } },
	{ option: '17', style: { backgroundColor: 'black', textColor: 'white' } },
	{ option: '34', style: { backgroundColor: 'red', textColor: 'white' } },
	{ option: '6', style: { backgroundColor: 'black', textColor: 'white' } },
	{ option: '27', style: { backgroundColor: 'red', textColor: 'white' } },
	{ option: '13', style: { backgroundColor: 'black', textColor: 'white' } },
	{ option: '36', style: { backgroundColor: 'red', textColor: 'white' } },
	{ option: '11', style: { backgroundColor: 'black', textColor: 'white' } },
	{ option: '30', style: { backgroundColor: 'red', textColor: 'white' } },
	{ option: '8', style: { backgroundColor: 'black', textColor: 'white' } },
	{ option: '23', style: { backgroundColor: 'red', textColor: 'white' } },
	{ option: '10', style: { backgroundColor: 'black', textColor: 'white' } },
	{ option: '5', style: { backgroundColor: 'red', textColor: 'white' } },
	{ option: '24', style: { backgroundColor: 'black', textColor: 'white' } },
	{ option: '16', style: { backgroundColor: 'red', textColor: 'white' } },
	{ option: '33', style: { backgroundColor: 'black', textColor: 'white' } },
	{ option: '1', style: { backgroundColor: 'red', textColor: 'white' } },
	{ option: '20', style: { backgroundColor: 'black', textColor: 'white' } },
	{ option: '14', style: { backgroundColor: 'red', textColor: 'white' } },
	{ option: '31', style: { backgroundColor: 'black', textColor: 'white' } },
	{ option: '9', style: { backgroundColor: 'red', textColor: 'white' } },
	{ option: '22', style: { backgroundColor: 'black', textColor: 'white' } },
	{ option: '18', style: { backgroundColor: 'red', textColor: 'white' } },
	{ option: '29', style: { backgroundColor: 'black', textColor: 'white' } },
	{ option: '7', style: { backgroundColor: 'red', textColor: 'white' } },
	{ option: '28', style: { backgroundColor: 'black', textColor: 'white' } },
	{ option: '12', style: { backgroundColor: 'red', textColor: 'white' } },
	{ option: '35', style: { backgroundColor: 'black', textColor: 'white' } },
	{ option: '3', style: { backgroundColor: 'red', textColor: 'white' } },
	{ option: '26', style: { backgroundColor: 'black', textColor: 'white' } },
];
console.log(data.length)

export const alternateNumbers = {
	0: 0,
	32: 1,
	15: 2,
	19: 3,
	4: 4,
	21: 5,
	2: 6,
	25: 7,
	17: 8,
	34: 9,
	6: 10,
	27: 11,
	13: 12,
	36: 13,
	11: 14,
	30: 15,
	8: 16,
	23: 17,
	10: 18,
	5: 19,
	24: 20,
	16: 21,
	33: 22,
	1: 23,
	20: 24,
	14: 25,
	31: 26,
	9: 27,
	22: 28,
	18: 29,
	29: 30,
	7: 31,
	28: 32,
	12: 33,
	35: 34,
	3: 35,
	26: 36,
};
